development:
  lw_system_id: 'Intel_UAT'
  lw_customer_id: 'Intel'
  lw_secret_key: 123456
  lw_modserver_url: 'modserver-v1-11-uat.stage.liveworld.com'
  kbsp_server_url: "http://review.kbsp.com:4001"
  fb_app_id: 300396973355596
  fb_app_secret: "bf5fc779a078df2442b90002057d78ee"
  fb_app_url: "http://apps.facebook.com/300396973355596"

test:
  lw_system_id: 'Intel_UAT'
  lw_customer_id: 'Intel'
  lw_secret_key: 123456
  lw_modserver_url: 'modserver-v1-11-uat.stage.liveworld.com'
  kbsp_server_url: "http://review.kbsp.com:3000"

production:
  lw_system_id: 'Intel_Will.I.Am'
  lw_customer_id: 'Intel'
  lw_secret_key: 'b1llAd@M$'
  lw_modserver_url: 'modserver-mercury.moderators.liveworld.com'
  kbsp_server_url: "http://review.kbsp.com:3000"
